/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 bearing.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/bearing.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Aro_externo.geometry} material={materials.Metal} />
      <mesh geometry={nodes.Aro_interno.geometry} material={materials.Metal} />
      <mesh geometry={nodes.Gomilla.geometry} material={materials.Gomilla} />
      <mesh geometry={nodes.Bolas.geometry} material={materials['Metal Bolas']} />
      <mesh geometry={nodes.Bronce.geometry} material={materials['Material.001']} />
    </group>
  )
}

useGLTF.preload('/bearing.glb')
