/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\bearingv2.glb 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export function Bearing(props) {
  const { nodes, materials } = useGLTF("/bearingv2.glb");
  const gomillaRef = useRef();
  const bolaRef = useRef();
  const rpm = 150

  useFrame((state,delta) =>{
    bolaRef.current.rotation.x +=delta*rpmToRadPerSecond(rpm)
  })
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Aro_externo.geometry} material={materials.Metal} visible={true}/>
      <mesh geometry={nodes.Aro_interno.geometry} material={materials.Metal} visible={true}/>
      <mesh
        geometry={nodes.Gomilla.geometry}
        material={materials.Gomilla}
        ref={gomillaRef}
        visible={false}
      />
      <mesh
        geometry={nodes.Bolas.geometry}
        material={materials.Metal_Bolas}
        ref={bolaRef}
        visible={true}
      />
      <mesh geometry={nodes.Bronce.geometry} material={materials.metalNegro} visible={true}/>
    </group>
  );
}


function rpmToRadPerSecond(rpm) {
  return rpm * (2 * Math.PI / 60);
}

useGLTF.preload("/bearingv2.glb");
